### PR TITLE
Fix exporting variables from function local scope

### PR DESCRIPTION
**Pull request by siteshwar**
While copying variables from function's local scope to a new scope,
variable attributes were not copied. Such variables were not marked
to be exported in the new function. For e.g.

function f2 { env | grep -i "^foo"; }
function f1 { env | grep -i "^foo"; f2; }
foo=bar f1

prints 'foo=bar' only once, but it should print be twice. This patch
fixes it.

Resolves: #32

### CODE REVIEW

**Comment by krader1961** [comment]
LGTM

**Comment by siteshwar** [comment]
@krader1961 Thanks for the review. However, I am bit skeptical about merging this change. I will let this pull request stay open for few more days and see if there are any objections. @sckendall2 it would help if you can explain where did you encounter this issue.

**Comment by sckendall2** [comment]
I don't remember how I encountered this issue.

But at the risk of talking your ear off, I'm not exaggerating much to say that it keeps me up at night. I work on the underpinnings of a large code base of KornShell (among other languages). This issue means that innocuous changes can break working scripts, and in a way that's subtle and hard to find by inspection.

Here's a simplistic example. We start with a working code snippet:
```Shell
function print_ids { ... | sort; }
LC_ALL=C print_ids > ids # C locale ensures consistent order
```
Now a well-meaning developer inserts a function wrapper to protect against variations in PATH:
```Shell
function sort { /usr/bin/sort "$@"; }
```
The wrapper breaks the snippet, because /usr/bin/sort no longer sees LC_ALL. If you imagine that these three lines of code are far away from each other, you can see how difficult it is to spot the problem.

This issue occurs only in ksh93,  not in mksh or other KornShell implementations I've checked.

**Comment by siteshwar** [comment]
@sckendall2 You have a fair point, so I am going to merge this change.

**Pull request merged**
