### PR TITLE
Remove support for OS/400 and MVS.

### PR DESCRIPTION
**Pull request by catull**
This  PR removes support for OS/400 and MVS.

### CODE REVIEW

**Comment by KeithBierman** [comment]
Without taking a position on "blind" , etc.


   - Remove support for OS/400 and MVS. They are not a first tier platforms


I think it would be clearer if this sort of thing were stated as "These are
not supported platforms" ... tiers would suggest that there would be some
other way for them to have their code supported (some PR to some other
repo?), which would seem quite different than what these PR's seem to be
accomplishing.


Keith Bierman
khbkhb@gmail.com
303 997 2749

**Comment by catull** [comment]
In FreeBSD, they distinguish 3 different tiers.

Tier 1 is supported architecture: x64, arm7, PPC and PPC64 etc
Tier 2 is development architecture.
Tier 3 is experimental architecture.

I think NetBSD and OpenBSD also use "tier N" naming.
Here tier is the CPU hardware.

Can't be directly applied to ksh93, as it is an application on those OS.

Your suggestion makes sense: "supported" / "not supported platform", will use it from now on.

**Comment by krytarowski** [comment]
NetBSD uses term tier with similar meaning 1-3.

**Comment by krader1961** [comment]
Closing without merging because this only affects the legacy Nmake build system which is code we're going to remove in its entirety in the near future. It does not affect building ksh using Meson. Also, we need to be careful about removing support for IBM "mainframes" that use EBCDIC which we still want to support.

**Comment by krader1961** [comment]
Also, phrases like "first tier platform" should be avoided. At least at this point in time. There are lots of legacy platforms we no longer want to support. For example, platforms that only have pre-ANSI C compilers. Or dead operating systems like Sequent Computer Systems DYNIX/3 (which I worked for and supported many years ago). Similar, clear cut, legacy support will be removed. But even if this PR affected more than the Nmake build tool it is not clear it clears that bar.

**Pull request closed without merging**
