### PR TITLE
Fix a crash when ksh is used as login shell

### PR DESCRIPTION
**Pull request by siteshwar**
Resolves: rhbz#1200534

### CODE REVIEW

**Comment by siteshwar** [comment]
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1200534 (private)

Patch: http://pkgs.fedoraproject.org/cgit/rpms/ksh.git/tree/ksh-20140801-arraylen.patch

**Comment by siteshwar** [comment]
It is a memory corruption. I could not reproduce it but the bug says it crashes with below lines when ksh is used as login shell:

```
function dlog
{
  fc -ln -0
}
trap dlog DEBUG
>/tmp/blah
```

**Comment by krader1961** [comment]
Thank you for including a link to the Redhat bugzilla issue but those are not visible to anyone without the requisite permission such as myself. Ideally the Redhat issues would be mirrored here or made publicly visible but that is hard to justify. Since I merged several of the Solaris OS patches without requiring more detail regarding the reason for the change I am in no position to ask that these (the Redhat Fedora patches) be held to a higher standard. At this point there are so many problems with the ksh code that I am willing to see any bug fixes merged if they do not have any obvious problems.

**Comment by siteshwar** [comment]
I did not realize that there were other private bugzillas than the one I mentioned in this pull request. I will try to make them public or put a short description of the discussion in related pull requests.

**Comment by krader1961** [comment]
Merged but with a tweak to explicitly initialize the static array. Technically it isn't necessary since static vars are supposed to be backed by zero filled pages of memory but I dislike relying on that subtlety since it is a bad habit that can cause people to omit the initialization for stack local vars where it is needed.

**Pull request closed without merging**
