### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Mliveon**

### CODE REVIEW

**Comment by mcepl** [comment]
This is just a vandalism, isn’t it? I think, this should be closed as WONTFIX.

**Comment by gordonwoodhull** [comment]
Unfortunately I've lost admin access to this repo with a job change. 

@lkoutsofios, are you able to close this? Would you consider finally setting this repo to read-only / archive?

**Comment by kdudka** [comment]
> This is just a vandalism, isn’t it? I think, this should be closed as WONTFIX.

Yep, I reported this SPAM account to GitHub on October 17th, got confirmation that my request was received but I am not sure whether any action has been taken since then.  The SPAM account still exists.

**Comment by ormaaj** [comment]
> Unfortunately I've lost admin access to this repo with a job change.
> 
> @lkoutsofios, are you able to close this? Would you consider finally setting this repo to read-only / archive?

kornshell.com still points here. presumably that's DGK's personal page and has never been updated.

@McDutchie 's project has put quite some effort into https://github.com/ksh93/ksh93-history and https://github.com/ksh93/ast-open-archive which preserves all the publicly available history that we know about, and should include everything available here.

(If anyone knows of anything missing there and knows how we could get our hands on it, we'd love to know!)

**Comment by hlangeveld** [comment]
FWIW, I've reported this as a Phishing attempt.

I had to do an internet search, as GitHub directs almost any questions regarding abuse towards their community or product pages.

**Comment by hlangeveld** [comment]
Any other initiative should probably be internal to AT&T and involve vendor relations or whatever the appropriate department is named.

**Comment by hlangeveld** [comment]
I _thought_ I had seen such an option before. Thanks for the hint.

**Pull request closed without merging**
