### PR TITLE
Remove unneeded redefinition of `sh_funscope`

### PR DESCRIPTION
**Pull request by siteshwar**

### CODE REVIEW

**Comment by krader1961** [comment]
This is a good example of why I opened issue #983. Rather than just removing these unused legacy interfaces one at a time I'd prefer to remove them all at the same time and rename the variants that include a date stamp to the simple name. If we ever again need to make a non-backward compatible API change I'd prefer to do it in a different manner.

**Comment by siteshwar** [comment]
@krader1961 Ok, shall I merge this ? I usually review code for each file one by one and find these unused functions. If you want to remove them all at once, I will stop opening such pull requests.

**Comment by krader1961** [comment]
Since we're talking about what I call a "mechanical" change that doesn't affect functionality it makes more sense to do it all as a single commit. Just remove all the legacy interfaces, rename the new ones introduced in 2012 to their legacy name, and remove *shell_api.h*.

**Comment by siteshwar** [comment]
Ok, will close this for now.

**Pull request closed without merging**
