### PR TITLE
Enable test cases for standard commands

### PR DESCRIPTION
**Pull request by siteshwar**

### CODE REVIEW

**Comment by siteshwar** [comment]
I think this should be fixed in Meson. I have opened an issue for it https://github.com/mesonbuild/meson/issues/3519

**Comment by krader1961** [comment]
Fails with the following one or both of the following errors on macOS, opensuse and ubuntu 16.04:

```
<E> builtins[811]: basename bound to /bin/basename but should be bound to /usr/bin/basename
<E> builtins[812]: cmp bound to /bin/cmp but should be bound to /usr/bin/cmp
```

**Comment by siteshwar** [comment]
@krader1961 Fixed.

**Comment by krader1961** [comment]
LGTM, in as much as it no longer introduces new test failures on the platforms I'm testing against :smile: Also, I have no objection to the text of the change. But I'm far from happy about how builtin commands of this sort are exposed and tested. That, however, is a discussion for another day.

**Pull request merged**
