### PR TITLE
Disable directory fd test for mkdir/rmdir/cat builtins

### PR DESCRIPTION
**Pull request by siteshwar**

### CODE REVIEW

**Comment by dannyweldon** [comment]
Please hold off on this as I have not had time to be able to respond again to #129

**Comment by siteshwar** [comment]
@dannyweldon There is a todo comment in the code and I am not ruling out the possibility to reenable this test. I am just disabling it for now.

**Comment by krader1961** [comment]
@dannyweldon, Don't panic. I, for one, have not reached a decision on whether all of those commands should be standard builtins. I think there are good arguments for and against. What @siteshwar and I are trying to do with these changes is just get the project into a state where we can switch to Meson for local and Travis builds. If and when it is decided that things like `cat` should continue to be standard builtins we'll ensure these tests are re-enabled and work.

**Comment by dannyweldon** [comment]
Thanks.  Okay, that's fine.

**Comment by krader1961** [comment]
Merged as commit d606a1314.

**Pull request closed without merging**
