### PR TITLE
Fallback version number should be configurable

### PR DESCRIPTION
**Pull request by siteshwar**
Related: #570

### CODE REVIEW

**Comment by krader1961** [comment]
LGTM from a correctness standpoint. However, I'm an worried about how this will be used. How will the OBS and Copr builds incorporate the correct version string? That is, how will the `-Dfallback-version-number='x.y.z'` build flag be determined? And why can't we just do the same thing automatically without requiring a config time flag? What is to keep those build systems from specifying a misleading version string?

**Comment by siteshwar** [comment]
@krader1961 See https://github.com/att/ast/pull/571/commits/eada2dce58bf7c27c406d4fbebdb11b1de070801

**Comment by krader1961** [comment]
Since I have almost zero experience with distro packaging (other than as a consumer) I'm going to trust that it's necessary to do what you're doing in those scripts rather than just let Meson run the `git describe`. And for testing purposes being able to set the semantic version string to an arbitrary value might be useful. So, LGTM.

**Comment by saper** [comment]
I'd reverse the logic not to require git at all if not needed: -Dversion-number shall it become and git being invoked only when not provided.

**Comment by krader1961** [comment]
@saper The problem is that doesn't fit well with the Meson DSL. Or at least I don't see an obvious, simple, way to do what you're describing. I don't doubt it could be done but since I'm not a distro maintainer I'm not motivated to figure out how to do it.

Everyone building from a git clone of the project with an available git command just runs `meson` and the correct version string will be extracted. Other situations should be limited to things like distro package builds where they may want more control over the version string anyway (e.g., to reflect locally applied patches). If they want that control and a) can't simply ensure a `git` command isn't found or b) the source tree doesn't contain the *.git* directory then they can add a trivial `git` script that does nothing more than echo the desired version string.

Having said all that if you create a PR that only uses `git` if `-Dversion-string` isn't provided we'd be happy to merge it.

**Comment by saper** [comment]
Ok, I'll be using bin/package for now :)

**Pull request merged**
