### PR TITLE
Modify regression test suite

### PR DESCRIPTION
**Pull request by siteshwar**
Taken from http://pkgs.fedoraproject.org/cgit/rpms/ksh.git/tree/ksh-20100826-fixregr.patch

### CODE REVIEW

**Comment by siteshwar** [comment]
I could not find reference to any bug for it.

**Comment by krader1961** [comment]
Merged.

**Comment by kdudka** [comment]
Any chance to make the commit messages actually useful?

The fact that you have modified regression test suite is pretty obvious from the diffstat.  It would help me (as well as anybody else investigating the change few years from now) if the commit message actually explained **why** the change was made.

**Comment by siteshwar** [comment]
@kdudka I usually leave references to related bugs in the commit messages. I tried to search for reference for this change, but could not find any. That's why I left this comment https://github.com/att/ast/pull/181#issuecomment-348731341.

**Comment by kdudka** [comment]
I agree that it is good to reference bug reports when available.  But even if you have a bug number to refer to, I do not think it should be used as substitution for a proper commit message.  The corresponding bug tracker might not be reachable when you need it later on.

Even for Github issues and PRs, there is no guarantee that people will be able to view them few years from now.  I am hereby asking you to make the commit messages useful on their own wherever possible.  Thanks in advance!

**Comment by siteshwar** [comment]
@kdudka Ok, I will try to add more description in the commit messages in future. Thanks!

**Pull request closed without merging**
