### PR TITLE
Support for the solaris 11.4 platform.

### PR DESCRIPTION
**Pull request by sneyx1234**
Draft preview.

### CODE REVIEW

**Comment by krader1961** [comment]
@sneyx123 I'm not sure what to do with this PR. It looks like you started with a commit much older than the `master` branch.

The first change simply adds the *bin/hosttype* script we renamed to *script/hosttype*. This was my first clue you are working with a very old copy of the source code.

The second commit seems to have reverted part of a previous change that we don't want reverted. And the `#ifndef BBI_SOL11_4` addition isn't how we want to handle such things if at all possible. It's preferable to have a platform neutral feature test. Not to mention you can't just ignore the case where `flags & OPT_domain` is true.

You then added `-D_ast_fltmax_double=1` and in a subsequent commit set it to zero. That's not the correct way to define a symbol that depends on build time feature tests. See the `#mesondefine` lines in *config_ast.h.in* and the `feature_data.set` directives in the various *meson.build* files.

Too, the `add_global_link_arguments('-lm', language: 'c')` line should not be needed. We already test if the platform has a `libm` library. See this block in *features/meson.build*:

```
# On some platforms the math functions (e.g., `sin()`) that we need are found in
# libc, on others they are found in libm.
libm_dep = cc.find_library('m', required: false, dirs: lib_dirs)
```

Lastly, your commit 570c9197 adds some quotes around shell vars. That change was already made on 2018-08-26, six months ago, via commit c26b74a02.

**Comment by sneyx1234** [comment]
> @sneyx123 I'm not sure what to do with this PR. It looks like you started with a commit much older than the `master` branch.
> 
> The first change simply adds the _bin/hosttype_ script we renamed to _script/hosttype_. This was my first clue you are working with a very old copy of the source code.

In this case there must be still a reference to bin/hosttype ... somewhere in context of conf.sh ... thats why it was added. 

So I will change the references? And then remove the added "bin/hosttype" file.

The references are here:
```
# find "."  -type d -name '.svn' -prune -o -type f -print | xargs grep bin/hosttype
./features/libpath.sh:  case $("$MESON_SOURCE_ROOT/bin/hosttype") in
./features/libpath.sh:else      case $("$MESON_SOURCE_ROOT/bin/hosttype") in
./build/meson-logs/meson-log.txt:+ /export/home/simon/ASTOPEN/GIT/sneyx1234-ast/bin/hosttype
./src/lib/libast/comp/conf.sh:HOST=`"$MESON_SOURCE_ROOT/bin/hosttype" | sed -e 's,[0123456789.].*,,' | tr abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ`
```

> The second commit seems to have reverted part of a previous change that we don't want reverted. And the `#ifndef BBI_SOL11_4` addition isn't how we want to handle such things if at all possible. It's preferable to have a platform neutral feature test. Not to mention you can't just ignore the case where `flags & OPT_domain` is true.

Sure, I must first understand since when "uname" has a option to output the "secure remote procedure call" domainname ... also why uname is bundled with ksh at all ... maybe its part of the AT&T build system? I would expect that "uname" is bunded with the kernel ... maybe in standalone enviroinments it make sense ... but standalone and RPC ?

> You then added `-D_ast_fltmax_double=1` and in a subsequent commit set it to zero. That's not the correct way to define a symbol that depends on build time feature tests. See the `#mesondefine` lines in _config_ast.h.in_ and the `feature_data.set` directives in the various _meson.build_ files.

Just dropped that line -- because "0" and "undef" is here the same. 

> Too, the `add_global_link_arguments('-lm', language: 'c')` line should not be needed. We already test if the platform has a `libm` library. See this block in _features/meson.build_:
> 
> ```
> # On some platforms the math functions (e.g., `sin()`) that we need are found in
> # libc, on others they are found in libm.
> libm_dep = cc.find_library('m', required: false, dirs: lib_dirs)
> ```

libm was not found by the meson so the problem must be fixed in that context:

```
Checking for size of "wchar_t" : 4
Compiler for C supports link arguments -Wl,--export-dynamic: NO
Checking for size of "long long" : 8
Library m found: NO
Library dl found: NO
Library execinfo found: NO
```


> Lastly, your commit [570c919](https://github.com/att/ast/commit/570c9197022dbef424c04f9fb11c17652adc8e26) adds some quotes around shell vars. That change was already made on 2018-08-26, six months ago, via commit [c26b74a](https://github.com/att/ast/commit/c26b74a021d2f7ea9ebfc50dc1ff61788136babd).

After the reference to bin/hosttype in context of "conf.sh" is adjusted to "scripts/hosttype" then this fault of me will become irrelevant.

**Comment by krader1961** [comment]
> In this case there must be still a reference to bin/hosttype

Yes, there is a reference to the *bin/hosttype* command in *features/libpath.sh*. I will fix that. What this tells us is that the special-case (i.e., error) path of that script has not been executed on any of the other platforms we have been using for testing.

**Comment by krader1961** [comment]
> libm was not found by the meson so the problem must be fixed in that context:

That is probably true. On OpenIndiana the libm detection works.  But I am using manual workarounds such as changing the */usr/bin/ld* command to be a link to */usr/gnu/bin/ld*.

Solaris is going to be a challenge due to its idiosyncratic support for universes (e.g., BSD versus SVR3 and SVR4) and other standards (e.g., SUSv2 versus SUSv3).

**Comment by sneyx1234** [comment]
> Yes, there is a reference to the _bin/hosttype_ command in _features/libpath.sh_. I will fix that. What this tells us is that the special-case (i.e., error) path of that script has not been executed on any of the other platforms we have been using for testing.

Also in ./src/lib/libast/comp/conf.sh .

**Comment by krader1961** [comment]
> Also in ./src/lib/libast/comp/conf.sh

Yes, that script as well. I'll fix that.

> also why uname is bundled with ksh at all

It is "bundled" (i.e., an optional builtin) because the AST/ksh team either needed it as a builtin in order to support platforms like UWIN or because they thought having a platform independent version of the command would be useful.

Other builtins like `cat` and `chmod` are much easier to justify because they are either used extremely frequently or the differences in APIs among the BSD/SysV/Linux flavors made using the command in a portable ksh script difficult.

**Comment by sneyx1234** [comment]
> > libm was not found by the meson so the problem must be fixed in that context:
> 
> That is probably true. On OpenIndiana the libm detection works. But I am using manual workarounds such as changing the _/usr/bin/ld_ command to be a link to _/usr/gnu/bin/ld_.
> 
> Solaris is going to be a challenge due to its idiosyncratic support for universes (e.g., BSD versus SVR3 and SVR4) and other standards (e.g., SUSv2 versus SUSv3).

Normally is the gcc only the second choice after the sun "cc":
``` 
         Name: developer/sunstudio12u1
       Summary: Sun Studio 12 update 1
      Category: Development/Suites
         State: Not installed
     Publisher: openindiana.org
       Version: 12.1.1
        Branch: 2018.0.0.5
Packaging Date: February 12, 2018 at 05:02:35 AM
          Size: 0.00 B
          FMRI: pkg://openindiana.org/developer/sunstudio12u1@12.1.1-2018.0.0.5:20180212T050235Z
```
.

**Comment by sneyx1234** [comment]
> Normally is the gcc only the second choice after the sun "cc":
And the real "ld" is located at /usr/ccs/bin/ld ... the "AT&T Cross Code System" ...
Oracle has recently replace /usr/css with symlinks ...

**Comment by krader1961** [comment]
> Normally is the gcc only the second choice after the sun "cc":

Yes, unless the user has explicitly requested a different compiler. Such as by doing this:

```
CC=gcc-8 AR=/usr/xpg4/bin/ar LD=/usr/gnu/bin/ld meson
```

Which is what I've needed to do up to this point just to make any progress building ksh on OpenIndiana. These types of hacks should not be necessary and, as we gain experience building on Solaris based distros, will hopefully be unnecessary.

**Comment by sneyx1234** [comment]
> > Normally is the gcc only the second choice after the sun "cc":
> 
> Yes, unless the user has explicitly requested a different compiler. Such as by doing this:
> 
> ```
> CC=gcc-8 AR=/usr/xpg4/bin/ar LD=/usr/gnu/bin/ld meson
> ```
> 
> Which is what I've needed to do up to this point just to make any progress building ksh on OpenIndiana. These types of hacks should not be necessary and, as we gain experience building on Solaris based distros, will hopefully be unnecessary.

From where have you taken python > 3.5 ?

**Comment by sneyx1234** [comment]
> > In this case there must be still a reference to bin/hosttype
> 
> Yes, there is a reference to the _bin/hosttype_ command in _features/libpath.sh_. I will fix that. What this tells us is that the special-case (i.e., error) path of that script has not been executed on any of the other platforms we have been using for testing.

So where is the coverage graph analysis for all involved script and program laguages? 
Who manage the test-vectors for it?

**Comment by sneyx1234** [comment]
> > > In this case there must be still a reference to bin/hosttype
> > 
> > 
> > Yes, there is a reference to the _bin/hosttype_ command in _features/libpath.sh_. I will fix that. What this tells us is that the special-case (i.e., error) path of that script has not been executed on any of the other platforms we have been using for testing.
> 
> So where is the coverage graph analysis for all involved script and program languages?
> Who manage the test-vectors for it?

Dont forget that "nv" is aka as "Cdt" ... and "Cdt" is also used by graphwiz, dotty ... so bug fixed are also relevant for the complete code circle. ... graphwiz is a nice tool to visualize coverage graphs for humans?

**Comment by sneyx1234** [comment]
FYI:
Support information for Openindiana platform:
```
As "root":
pkg install pkg:/developer/versioning/git
pkg install pkg:/developer/gnu-binutils
pkg install pkg:/developer/gcc-7
pkg install pkg:/developer/build/ninja
pkg install pkg:/runtime/python-35
pkg install pkg:/system/header
```
Also as "root" on clone of sneyx1234/meson (For security reasons meson must segregate itself soon :-1: ):
```
python3 setup.py install
```

As "any looser" on clone of sneyx1234/ast (Yes AR is "ld"  :-1: ):
```
env CC="gcc-7" AR="/usr/gnu/bin/ld"  LD="/usr/gnu/bin/ld" meson build
```

Output:
```
The Meson build system
Version: 0.50.999
Source dir: /export/home/simon/sneyx1234-ast
Build dir: /export/home/simon/sneyx1234-ast/build
Build type: native build
Project name: ksh93
Project version: undefined
Native C compiler: gcc-7 (gcc 7.3.0 "gcc-7 (OpenIndiana 7.3.0-OI-2) 7.3.0")
WARNING: Unknown CPU family 'i86pc', please report this at https://github.com/mesonbuild/meson/issues/new with theoutput of `uname -a` and `cat /proc/cpuinfo`
Build machine cpu family: i86pc
Build machine cpu: i86pc
Compiler for C supports arguments -Werror=implicit: YES
Checking for size of "void*" : 4
Checking for size of "int" : 4
Checking for size of "long" : 4
Checking for size of "size_t" : 4
Checking for size of "off_t" : 8
Checking for size of "int32_t" : 4
Checking for size of "wchar_t" : 4
Compiler for C supports link arguments -Wl,--export-dynamic: NO
Checking for size of "long long" : 8
Library m found: NO
Library dl found: NO
Library execinfo found: NO
Library iconv found: NO
Library catgets found: NO
Has header "execinfo.h" : YES
Has header "stdlib.h" : YES
Has header "malloc.h" : YES
Has header "filio.h" : NO
Has header "sys/filio.h" : YES
Checking for function "lchmod" : NO
Checking for function "sigqueue" : YES
Checking for function "isnanl" : NO
Checking for function "eaccess" : NO
Checking for function "euidaccess" : NO
Checking for function "faccessat" : YES
Checking for function "mkostemp" : YES
Checking for function "strlcat" : YES
Checking for function "utimensat" : YES
Checking for function "sysinfo" : YES
Checking for function "pipe2" : YES
Checking for function "syncfs" : NO
Checking for function "nexttowardl" with dependency -lm: NO
Checking for function "expm1l" with dependency -lm: NO
Checking for function "log1pl" with dependency -lm: NO
Checking for function "remainderl" with dependency -lm: NO
Checking for function "log2l" with dependency -lm: NO
Checking for function "tgammal" with dependency -lm: NO
Checking for function "lgammal" with dependency -lm: NO
Checking if "fchmod() after socketpair() shutdown()" runs: DID NOT COMPILE
Checking if "max signal number" runs: YES
Checking whether type "struct dirent" has member "d_fileno" : NO
Checking whether type "struct dirent" has member "d_ino" : YES
Checking whether type "struct dirent" has member "d_reclen" : YES
Checking whether type "struct dirent" has member "d_type" : NO
Checking whether type "struct dirent" has member "d_namlen" : NO
Checking whether type "struct stat" has member "st_mtim" : YES
Checking if "poll() exists and is worth using" runs: YES
Checking if "posix_spawn() exists and is worth using" runs: YES
Checking if "Check if -D_FILE_OFFSET_BITS=64 works with fts functions" compiles: NO
Program tput found: YES (/usr/bin/tput)
Program ed found: YES (/usr/bin/ed)
Program atos found: NO
Program addr2line found: YES (/usr/gnu/bin/addr2line)
Has header "dl.h" : NO
Has header "dlfcn.h" : YES
Has header "dll.h" : NO
Has header "rld_interface.h" : NO
Has header "mach-o/dyld.h" : NO
Has header "sys/ldr.h" : NO
Library dl found: NO
Checking for function "dlopen" with dependency -ldl: YES
Checking for function "dllload" with dependency -ldl: NO
Checking for function "loadbind" with dependency -ldl: NO
Checking if "_DYNAMIC check" runs: DID NOT COMPILE
Checking for function "clock_gettime" : YES
Checking for function "gettimeofday" : YES
Has header "sys/syscall.h" : YES
Has header "sys/systeminfo.h" : YES
Has header "sys/syssgi.h" : NO
Checking for function "syscall" : NO
Checking for function "systeminfo" : NO
Configuring config_ast.h using configuration
Checking if "gcc 4.1+ 64 bit memory atomic operations model" links: YES
Program sh found: YES (/usr/bin/sh)
src/cmd/ksh93/tests/meson.build:86: WARNING: skipping io/shcomp on sunos
src/cmd/ksh93/tests/meson.build:86: WARNING: skipping set/shcomp on sunos
src/cmd/ksh93/tests/meson.build:86: WARNING: skipping treemove/shcomp on sunos
Build targets in project: 128
Found ninja-1.8.2 at /usr/bin/ninja
```
Current Ninja errors:
```

# ninja -k 99 -C build | grep "^FAILED"
FAILED: src/lib/libast/e416224@@ast@sta/port_astconf.c.o 
FAILED: src/lib/libast/tests/path/0363e74@@pathbin@exe/pathbin.c.o 
FAILED: src/lib/libast/e416224@@ast@sta/misc_fgetcwd.c.o 
FAILED: src/lib/libast/libenv.a 
FAILED: src/lib/libcmd/libcmd.a 
FAILED: src/lib/libdll/libdll.a 
FAILED: src/lib/libdll/libsample.so 
FAILED: src/cmd/ksh93/a265ff0@@ksh@sta/bltins_cd_pwd.c.o 
```

**Comment by sneyx1234** [comment]
Also interessting is that "meson" works in solaris 11.4 if the project filesystem is are NFS/CIFS shared ZFS with "Non Blocking mandatory locks" property "nbmand" turn "on" ... and openindiana has a issues ... must be on local ZFS filesystems ... :-1:

**Comment by sneyx1234** [comment]
### Like to debug the debugger  :-)

Startimg the "gdb" on solaris 11.4 sparc with current ksh2020 as argument: 
``` 
# gdb ./build/src/cmd/ksh93/ksh
GNU gdb (GDB) 8.0
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "sparc-sun-solaris2.11".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./build/src/cmd/ksh93/ksh...done.
(gdb) 
```

Enter "run" in gdb:
```
(gdb) run
Starting program: /net/bbi030/export/bkup-R2008/pub/T4-2/repos_3s/trunk/xops/ASTOPEN/GIT/sneyx1234-ast/build/src/cmd/ksh93/ksh
#
```

Now in the ksh interpreter source the script of #1297 and enter interactive final "typeset -p .sh.type" to trigger the violation:

```
# . /net/bbi030/export/bkup-R2008/pub/T4-2/repos_3s/trunk/xops/NS_simple.env
namespace sh.type
{
        typeset -r -s -u -i _Bool=false
}
namespace sh.type
{
        typeset -r -s -u -i _Bool=false
        typeset -r typ1='Sample'
}
/net/bbi030/export/bkup-R2008/pub/T4-2/repos_3s/trunk/xops/ASTOPEN/GIT/sneyx1234-ast/build/src/cmd/ksh93/ksh: .[14]: typ1: var11: only simple variables can be exported
#

# typeset -p .sh.type
### 5321 Function backtrace:
1   handle_sigsegv + 24
2   __sighndlr + 12
3   call_user_handler + 852
4   sigacthandler + 84
5   nv_getval + 28
6   sh_funscope + 2916
7   sh_funct + 1112
8   sh_fun + 1164
9   lookup + 576
10  lookups + 28
11  nv_getv + 348
12  nv_getval + 600
13  local_exports + 84
14  scanfilter + 944
15  nv_scan + 224
16  sh_funscope + 700
17  sh_funct + 1112
18  sh_fun + 1164
19  lookup + 576
20  lookups + 28
/builds/ulhg/workspace/Solaris_11u4/Userland/full-build/02b-build-sparc/components/gdb/gdb-8.0/gdb/target.c:2410: internal-error: void target_mourn_inferior(ptid_t): Assertion `ptid_equal (ptid, inferior_ptid)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Quit this debugging session? (y or n) y

This is a bug, please report it.  For instructions, see:
<http://www.gnu.org/software/gdb/bugs/>.

/builds/ulhg/workspace/Solaris_11u4/Userland/full-build/02b-build-sparc/components/gdb/gdb-8.0/gdb/target.c:2410: internal-error: void target_mourn_inferior(ptid_t): Assertion `ptid_equal (ptid, inferior_ptid)' failed.
A problem internal to GDB has been detected,
further debugging may prove unreliable.
Create a core file of GDB? (y or n) y
Abort(coredump)
#
```

Now check who has dumped the core:
```
# file core
core:           ELF 64-bit MSB core file SPARCV9 Version 1, from 'gdb'
````

**Comment by sneyx1234** [comment]
As always ... forget GNU ... GNU is not UNIX ... take a real debugger:
```
:# mdb ./build/src/cmd/ksh93/ksh
ksh> :r
mdb: forksys detected: follow (p)arent or (c)hild? p
mdb: target forked child process 5382 (debugger following parent)
mdb: forksys detected: follow (p)arent or (c)hild? p
mdb: target forked child process 5383 (debugger following parent)
mdb: forksys detected: follow (p)arent or (c)hild? p
mdb: target forked child process 5384 (debugger following parent)
mdb: forksys detected: follow (p)arent or (c)hild? p
mdb: target forked child process 5385 (debugger following parent)
[simon@bbikz9002:sneyx1234-ast]:809:# mdb: forksys detected: follow (p)arent or (c)hild? p
mdb: target forked child process 5386 (debugger following parent)

[simon@bbikz9002:sneyx1234-ast]:809:# . /net/bbi030/export/bkup-R2008/pub/T4-2/repos_3s/trunk/xops/NS_simple.env
namespace sh.type
{
        typeset -r -s -u -i _Bool=false
}
namespace sh.type
{
        typeset -r -s -u -i _Bool=false
        typeset -r typ1='Sample'
}
ksh: .[14]: typ1: var11: only simple variables can be exported
[simon@bbikz9002:sneyx1234-ast]:810:# typeset -p .sh.type
mdb: stop on SIGSEGV
mdb: target stopped at:
nv_getval+0x1c: ldx       [%g1 + 0x48], %g1
mdb: You've got symbols!
Loading modules: [ libc.so.1 ld.so.1 ]
ksh:5381*>

```

**Comment by sneyx1234** [comment]
Argument given to nv_getval from caller sh_funscope is a simple zero:

Stack backtrace with arguments from within mdb:
```
ksh:5418*> $c
nv_getval+0x1c(0, 100314020, 0, 0, ffffffff7ffff7a8, 0)
sh_funscope+0xb64(1002e9f30, 1, ffffffff7fffd328, 0, ffffffff7fffd1d8, 4)
sh_funct+0x458(1002e9f30, 1003437d0, 1, ffffffff7fffd328, 0, 4)
sh_fun+0x48c(1002e9f30, 1003437d0, 100342530, 0, 0, 0)
lookup+0x240(100342530, 0, 0, 100343ac0, 0, 0)
lookups+0x1c(100342530, 100343ac0, b400, ffffffff7f029948, ffffffff7f028000, 0)
nv_getv+0x15c(100342530, 100343ac0, 0, 73, 10035dfb0, 0)
nv_getval+0x258(100342530, 400, 0, 0, 0, 10013a9d4)
local_exports+0x54(100342530, ffffffff7fffdb70, 8, 0, 0, ffffffff7fffd960)
scanfilter+0x3b0(100315d60, 100342530, ffffffff7fffda78, 2d, 498, 1003437b0)
nv_scan+0xe0(100315d60, 1000a5d2c, ffffffff7fffdb70, 2000, 82000, ffffffff7fffdb90)
sh_funscope+0x2bc(1002e9f30, 1, ffffffff7fffdf68, 0, ffffffff7fffde18, 4)
sh_funct+0x458(1002e9f30, 1003437d0, 1, ffffffff7fffdf68, 0, 4)
sh_fun+0x48c(1002e9f30, 1003437d0, 100343750, 0, 0, 0)
lookup+0x240(100343750, 0, 0, 100343a00, ffffffff7fff90f8, 1)
lookups+0x1c(100343750, 100343a00, ffffffff7fffe3e0, 7479703100000000, 38, 101010101010101)
nv_getv+0x15c(100343750, 100343a00, 100032ef8, 1002dbb30, 0, 100324736)
nv_getval+0x258(100343750, 2000, 100312a91, 2d, 498, 1003437b0)
print_namval+0x7b0(1002dbd60, 100343750, 0, ffffffff7fffe900, 80000, 0)
print_scan+0x4e4(1002dbd60, 80000, 100318d30, 0, ffffffff7fffe900, 1)
print_value+0x278(1002dbd60, 100318de0, ffffffff7fffe900, 0, 0, 0)
setall+0xc78(100312b48, 20000, 100315d60, ffffffff7fffe900, 0, 100312a91)
b_typeset+0x1428(3, 100312b40, 1002ea480, 2, 7, ffffffff7f5c2a40)
sh_exec+0x1f6c(1002e9f30, 100312aa0, 24, ffffffff7ffff240, 0, 0)
exfile+0xebc(1002e9f30, 0, 0, 100319ee0, 7, 1002dcf10)
sh_main+0x1138(1, ffffffff7ffff5b8, 0, 0, 0, 0)
main+0xc0(1, ffffffff7ffff5b8, ffffffff7ffff5c8, 100000, 0, 0)
_start+0x64(0, 0, 0, 0, 0, 0)
ksh:5418*>
```

**Comment by sneyx1234** [comment]
There is only one call:
```
nv_getval(sh_scoped(shp, IFSNOD));
```
Looks like a "IFS" node ... the "Input Field Separator" variable ... very very interessting ... this one is not only the input separator ... its also the  output field separator for very cool stuff.

**Comment by sneyx1234** [comment]
If the discipline function (object method) is changed in this abtract syntax notated OBJECT-TYPE from:

```
        function get
        {
                .sh.value="'Sample'";
        }
```
To combined with the knowledge of the debugging result so far:

```
        function get
        {
                IFS=$' \t\n'
                .sh.value="'Sample'";
        }
```

We get no "core" dump ... ... ...
... ... ... If a functon is defined with the "function" keyword (not the old style with "()" literals ) variabled defined with the "typeset" keyword have function static scope ... but we are not in the **""** namespace ... the definition is in the relativistic world of A. Einstein ... the name of the eigenvector is called ".sh.type" or similar ?? But variables defined in functions without the "typeset" keyword are normaly in the global namespace **""** ... here it falls into the parent compound space of the just defined user defined type for the later variable/object instantiation.

**Comment by sneyx1234** [comment]
N.b.: Instead of the "core dump" it looks like this:

```
# typeset -p .sh.type
namespace sh.type
{
        IFS=$' \t\n'
        typeset -x -r typ1='Sample'
}
```

**Comment by sneyx1234** [comment]
Root cause analysis is hereby complete ... solution of #1297 is to insert/clone the parser / generator variable IFS at the right line :-)

**Comment by sneyx1234** [comment]
Indexed arrays of the user defined type also working ... without put() discipline its little bit useless ... i will not reveal all secrets at once -- the notice about the objects can not inherited by UNIX should be later removed ... everybody know that ...:

```
# typ1 var12_arr=( alpha beta gamma )
ksh93: typ1: var12_arr: only simple variables can be exported
# typeset -p var12_arr
typ1 -a var12_arr=($'\'Sample\'' $'\'Sample\'' $'\'Sample\'')
```

And remember you can call "typ1 -help" ... so associative arrays of the object will also work :-)

**Comment by sneyx1234** [comment]
Someone has removed the copyright message of "David Korn" and the other team members... so the change has to be reverted now.

**Comment by sneyx1234** [comment]
```
# typ1 -A var13_asso
ksh93: typ1: var13_asso: only simple variables can be exported

# var13_asso[alpha]="one"
# var13_asso[beta]="two"
# var13_asso[gamma]="three"

# typ1
typ1 var11='Sample'
typ1 -a var12_arr=($'\'Sample\'' $'\'Sample\'' $'\'Sample\'')
typ1 -A var13_asso=([alpha]=$'\'Sample\'' [beta]=$'\'Sample\'' [gamma]=$'\'Sample\'')

# typeset -p var13_asso
typ1 -A var13_asso=([alpha]=$'\'Sample\'' [beta]=$'\'Sample\'' [gamma]=$'\'Sample\'')
#
```

**Comment by sneyx1234** [comment]
No comments:
```
# unset var12_arr[0]
# typ1
typ1 var11='Sample'
typ1 -a var12_arr=([1]=$'\'Sample\'' [2]=$'\'Sample\'')
typ1 -A var13_asso=([alpha]=$'\'Sample\'' [beta]=$'\'Sample\'' [gamma]=$'\'Sample\'')
#
# print -v var12_arr
(
        [1]=$'\'Sample\''
        [2]=$'\'Sample\''
)
#
```

**Comment by sneyx1234** [comment]
Combinations "compound" with "index array" and "assocative array" possible never tested have issues:

```
# typeset -C Universe
# typ1 -a Universe.planet
ksh93: typ1: Universe.planet: only simple variables can be exported
# Universe.planet[1]="earth"
# Universe.planet[2]="venus"
# Universe.planet[3]="mercury"
# typ1 -A Universe.sparcs
# Universe.sparcs[tetra]="one two three four"
# Universe.sparcs[penta]="5 ?"
# typeset -p Universe
typeset -C Universe=(typ1 -a planet=([1]=$'\'Sample\'' [2]=$'\'Sample\'' [3]=$'\'Sample\'');()
# print -v Universe
(
        typ1 -a planet=(
                [1]=$'\'Sample\''
                [2]=$'\'Sample\''
                [3]=$'\'Sample\''
        )
(
)
# 
```

**Comment by krader1961** [comment]
I've finally managed to build ksh on OpenIndiana (a Solaris clone). I'm seeing 25 unit test failures.

@sneyx1234, Thanks for prompting us to consider supporting Solaris. But this PR has too many problems to be merged. I also cannot figure out what the problem is in your most recent [comment](https://github.com/att/ast/pull/1301#issuecomment-489345394). I encourage you to open issues about such problems but with more detail regarding the expected versus actual behavior.

This PR does not merge cleanly. Beyond that issue several of the changes in this PR are incompatible with how we want to handle platform specific features. So I'm going to close this. I have managed to build ksh and execute its unit tests on OpenIndiana (a Solaris fork) after a lot of effort. I will merge those changes soon. That should make it easier for other people to experiment with this project on Solaris based distros.

**Comment by sneyx1234** [comment]
### Advanced Topics

```
# cat NS_simple.env
typeset -p .sh.type
typeset -Ttyp1 typ1=(

        typeset store=$'(Empty)'

        function set
        {
                _.store="${.sh.value}"
        }

        function get
        {
                IFS=$' \t\n'

                .sh.value="${_.store}"
        }

)

typeset -p .sh.type

typ1
typ1 var11
```

My "nounset" option is normally active ... thats not the factory default ... so switch to default first:
```
# set +o nounset
# set +o
set --default --bgnice --braceexpand --emacs --ignoreeof --multiline --viraw
```

Source the modified version of #1297 and look thru the relativistic introscope:
```
# . ./NS_simple.env
namespace sh.type
{
        :
}
namespace sh.type
{
        typeset -r -b -L 4 typ1=
}
ksh93: .[23]: typ1: var11: only simple variables can be exported
#
```

Fine so far ... but now activate the "nounset" option and that reveals that the discipline function is called ... a little bit a intermix of stdout and stderr:
```
# typeset -p .sh.type
namespace sh.type
{
        IFS=$' \t\n'
        typeset -x -r -b -L 4 typ1=
}

# set -o nounset
# set +o
set --default --bgnice --braceexpand --emacs --ignoreeof --multiline --nounset --viraw

# typeset -p .sh.type
namespace sh.type
{
        IFS=$' \t\n'
        typeset -x -r -b -L 4 ksh93: typeset: typ1.get: line 15: _.store: parameter not set
ksh93: typeset: typ1.get: line 15: _.store: parameter not set
typ1=()
}
```

N.b.: that "object" ... the "instantiated type" is usable:
```
# print $var11
(Empty)

# var11="(Bang)"

# print $var11
(Bang)
# print -nv var11 | xxd
00000000: 05a9 e0                       

# typ1
typ1 var11=(Bang)
```

**Comment by sneyx1234** [comment]
Solaris 11.4 knows "O_DIRECTORY" for openat() and Openindiana not ... 
```
# find /usr/include/. -type f | xargs grep O_DIRECTORY
/usr/include/./sys/file.h:#define       FDIRECTORY      0x1000000       /* O_DIRECTORY = 0x1000000 */
/usr/include/./sys/fcntl.h:#define      O_DIRECTORY     0x1000000 /* open() fails for non-directory file */
```

**Comment by krader1961** [comment]
@sneyx1234 You should open issues when you find what appear to be bugs. Adding a comment to an unrelated PR is not helpful.

**Pull request closed without merging**
