### PR TITLE
Update changelog with stable version number

### PR DESCRIPTION
**Pull request by siteshwar**

### CODE REVIEW

**Comment by krader1961** [comment]
Shouldn't this also update *meson_options.txt*? Otherwise, LGTM, although I'm ambivalent about adding a `-stable` suffix. Personally I think the lack of an explicit `alpha`, `beta`, or git commit ID suffix implies it is a stable release. Explicitly saying it is a stable version seems superfluous.

**Comment by kdudka** [comment]
+1 for omitting the suffix on stable release(s)

**Comment by siteshwar** [comment]
> +1 for omitting the suffix on stable release(s)

Fixed

**Comment by siteshwar** [comment]
> Shouldn't this also update meson_options.txt? 

I will do that through a separate commit.

**Pull request merged**
