### PR TITLE
Remove special sub-variables from enum, integer and float types

### PR DESCRIPTION
**Pull request by siteshwar**
These sub-variables were added after last stable release and we fail to
see any value in adding them to next release.

### CODE REVIEW

**Comment by krader1961** [comment]
LGTM

**Comment by melbit-dannyw** [comment]
Please hold off on this for the moment as I would like to continue the discussion.

**Comment by krader1961** [comment]
@melbit-dannyw This PR commit message should have mentioned issue #1017. I look forward to seeing how you justify retaining these attributes. While introspection is generally a net positive this seems to me to be a case where the added complexity cannot be justified. In what universe will anyone writing a ksh script utilize the feature being removed to affect its behavior?

**Comment by dannyweldon** [comment]
Yes.  I will continue the discussion in #1017.

**Pull request merged**
