### PR TITLE
Fix a crash after unsetting a function

### PR DESCRIPTION
**Pull request by siteshwar**
Resolves: rhbz#1105138

### CODE REVIEW

**Comment by siteshwar** [comment]
This is the reproducer for the crash :
```
function ftest {
    ftest2
}

function ftest2 {
    unset -f ftest
}

ftest
```

however I could not reproduce the crash with latest master. Still opening this pull request for review, if I missed anything.

**Comment by siteshwar** [comment]
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1105138

Patch: http://pkgs.fedoraproject.org/cgit/rpms/ksh.git/tree/ksh-20120801-fununset.patch

**Comment by siteshwar** [comment]
The bug is private but I have provided testcase for it in https://github.com/att/ast/pull/186#issuecomment-348797139 from bugzilla.

**Comment by krader1961** [comment]
My reading of the code suggests that this problem can no longer happen. So while the extra condition guarding the decrement of `np->nvalue.rp->running` can't cause any problems it also should never keep the decrement from being done. So I'm going to close this as unneeded.

**Pull request closed without merging**
