### PR TITLE
Set correct scope for readonly variables

### PR DESCRIPTION
**Pull request by siteshwar**

### CODE REVIEW

**Comment by perette** [comment]
I have not managed to grok the name-value code, so all I can really say is, these changes fix the behavior.

**Comment by krader1961** [comment]
This also seems to leave a related bug. Shouldn't `readonly x=y` be equivalent to `typeset -r x=y`? Which means that when run inside a function it shouldn't mutate the value in outer scopes? Run the following with and without the proposed fix:

```
abc=ABC
tro=TRO
foo=FOO
function test_func {
    readonly foo="bar"
    typeset -r tro=temp
    typeset abc=def
    echo inside foo $foo
    echo inside tro $tro
    echo inside abc $abc
}
test_func
echo outside foo $foo
echo outside tro $tro
echo outside abc $abc
```

Notice how `$foo` outside the function gets mutated but `$tro` doesn't.

**Comment by perette** [comment]
@krader Good finds.  I agree this behavior is inconsistent, and probably a different bug.

Your test script exposes interesting behavior:
```
function foo {
   readonly x=fish
    echo inside $x
}
echo outside $x
x=whale
```

So it looks like the original implementation *creates a local variable*, but *put the contents into a global of the same name*.  That global lacks the readonly flag, which is assigned to the local.

So the question is, what *should* readonly do when given an assignment?  Create a local, equivalent to `typeset -r`, or create a global variable?  The local feels right, but I can see an argument that if you're really making a constant, it might as well go in the global scope.  `bash` does the global scope, so that weighs heavily in favor of the global.

**Comment by perette** [comment]
If it's supposed to be equivalent to `typeset -r` (and that does seem like the natural thing), why isn't it just implemented with an `alias readonly=typeset -r`?  Given `float`, `integer`, and several other types are really just aliases, I'd have expected that approach unless `readonly` was meant to do something different.

If we do want to refactor it to be `typeset -r`, is it better to simplify by dropping the code and adding a predefined alias?

If we want to go with the bash-compatible behavior (which I agree with Krader may be a non-backward compatible fix), the man pages should get updated to be explicit about this deviant behavior.

**Comment by krader1961** [comment]
Is `readonly` supposed to mimic `export`? The latter is not equivalent to `typeset -x` since it does not create a locally scoped exported var.  But note that `export` is explicitly documented not to be equivalent:

> The export command is the same as typeset -x  except  that  if you  use  export  within  a  function, no local variable is created.

No such caveat appears for the `readonly` documentation. Oversight in the documentation? Or deliberate in which case the implementation is wrong.

**Comment by krader1961** [comment]
The fact `readonly` isn't implemented as an alias for `typeset -r` sort of suggests the documentation of `readonly` should have the same caveat as `export`. This is reinforced by the fact both commands are implemented by the same function.

**Comment by perette** [comment]
I'm leaning toward readonly mimicking export.  Imagine the use case of a function load_program_configuration that reads some config (say, paths and stuff), and wants to stick it in global readonly variables for the rest of the program to use.  But there's no way to do that inside the function if `readonly` === `typeset -r`, since it would instead create locals, which would disappear on return.  You'd have to read the variables inside function, then readonly them in the main--but that breaks the modularity of having the function.

**Comment by krader1961** [comment]
@perette Just to be clear.... You seem to be arguing for the documentation of `readonly` to include the same caveat as `export`. That is okay as far as I am concerned. As I mentioned earlier the fact both `readonly` and `export` are implemented by the same function (something I consider a bogosity, they should be separate functions) strongly suggests that `readonly` is meant to create a global var rather than a function scoped var like `typeset -r`. However, it is still inconsistent and broken in other ways.

What happens if you do `export x=y` inside and outside a function? Now consider what happens if you do `readonly x=y` inside and outside a function (i.e., marking it readonly before the function is run). What happens if you run the function more than once? This is pretty clearly something the original ksh team either didn't think deeply about or some fundamental implementation errors were made.

**Comment by krader1961** [comment]
@siteshwar I'm inclined to move this discussion to issue #881 and give it a few weeks, better would be a couple of months, to see what others think should be the correct behavior. And since it is currently broken in a manner that makes it unusable (in ksh93u+ as well) we presumably don't have to worry about backward compatibility.

**Comment by krader1961** [comment]
Closing this since there is a debate regarding the desired behavior in issue #881 with the current consensus being that the behavior implemented by this PR may be correct but is not optimal.

**Pull request closed without merging**
