### PR TITLE
Add info about ast mailing list

### PR DESCRIPTION
**Pull request by siteshwar**

### CODE REVIEW

**Comment by krader1961** [comment]
LGTM in so far as I don't see any obvious typos or grammatical errors. I do have concerns about encouraging people to subscribe to a mailing list not under the control of the OSS community and which has so little traffic that for all intents and purposes the lists are dead. But since the lists still exist we might as well document how to subscribe to them.

**Comment by xosevp** [comment]
> I do have concerns about encouraging people to subscribe to a mailing list not under the control of the OSS community and which has so little traffic that for all intents and purposes the lists are dead.

There are still 143 people in developers list, and 294 in users.
Some of them(developers list) from unix companies:
      1 cn.fujitsu.com
      1 hp.com
      1 in.ibm.com
      1 natlab.research.philips.com
      1 suse.com
      2 redhat.com
      2 suse.de
      3 att.com
      3 research.att.com
      7 oracle.com

Maybe a new list could be set up in infradead or vger.

**Comment by siteshwar** [comment]
@xosevp Are you aware if there is any commitment from AT&T to keep these lists running ? If they are not willing to keep it maintained then we should probably start looking for options.

I was discussing this issue with @kdudka and @msekletar yesterday and it turns out that most of the new projects are using Google groups these days.

**Comment by xosevp** [comment]
> @xosevp Are you aware if there is any commitment from AT&T to keep these lists running ?

I have no idea, you should ask current sysadmin: Lefteris Koutsofios <ek@DELETEresearch.att.com> / <mailman@DELETElists.research.att.com>

**Pull request merged**
