### PR TITLE
FreeBSD seems to undefine ALIGN in <sys/param.h>

### LINKED ISSUE #26: nmake fails to build on FreeBSD 11.0 and 11.1
This is probably the wrong place to get help. I'm trying to get a recent version of ksh going so I can install CDE. When I run ./bin/package make, it gives me this error and fails compiling ast.

`mamake [cmd/nmake]: *** exit code 1 making expand.o
+ nmake --base --compile '--file=/home/wfisher/ast/src/cmd/nmake/Makerules.mk'
/bin/sh: nmake: not found
mamake [cmd/nmake]: *** exit code 127 making Makerules.mo
mamake: *** exit code 1 making cmd/nmake
package: make: errors making /home/wfisher/ast/arch/freebsd11.amd64/bin/nmake`

I don't know if I'm compiling things wrong or missing a dependency but the Googles hasn't turned up any help.

Thanks!!

### PR DESCRIPTION
**Pull request by saper**
Fixes #26, #48

### CODE REVIEW

**Comment by siteshwar** [comment]
Thanks for the pull request. Now I need to set up a FreeBSD system to test it. :)

**Comment by saper** [comment]
Well, it fails badly on Linux :)

**Comment by siteshwar** [comment]
Thanks for verifying our Travis set up :)

**Comment by saper** [comment]
Alternatively we could rename `ALIGN`, should work for all platforms...

**Comment by siteshwar** [comment]
I updated the commit message and merged it with 4dccf5f

**Comment by siteshwar** [comment]
It turns out it broke compilation on Linux. I have put a quick fix in #77

**Comment by saper** [comment]
Thanks!

**Pull request closed without merging**
