### PR TITLE
Fix warning missing braces around initializer

### PR DESCRIPTION
**Pull request by catull**
This PR eliminates all but one warning like this:

```c
../src/lib/libast/misc/error.c:60:1: warning: missing braces around initializer [-Wmissing-braces]
 {
 ^
../src/lib/libast/misc/error.c:66:2:
  0,0,0,0,0,0,0,  /* old empty context  */
  {            }
```
Incidentally, the example shown above just happens to be the only one which is still around after this PR.

### CODE REVIEW

**Comment by krader1961** [comment]
At least part of this PR is wrong as tests on macOS now has a huge number of SIGSEGV failures such as this one:

```
0   dump_backtrace + 69
1   handle_sigsegv + 25
2   _sigtramp + 26
3   3   ???                                 0x00007fffde11e39e 0x0 + 140736919102366
4   _ast_setlocale + 2010
5   init + 84
6   optget + 862
7   sh_argopts + 378
8   sh_init + 3016
9   sh_main + 94
10  main + 38
11  start + 1
```

**Comment by catull** [comment]
Yeah, working on it.

**Comment by catull** [comment]
Strange how Travis CI counts failures.

The Fedora build fails with coprocess(shcomp) and times out on signal(C.UTF-8), yet the summary is:
```log
OK:       154
FAIL:       2
SKIP:       0
TIMEOUT:    1
```

The OpenSUSE build fails the test signal(shcomp).

**Comment by krader1961** [comment]
The failed test counts are weird due to problems with this project and its associated unit tests. Don't worry too much about that. Several of the unit tests, such as the `signal` tests, are extremely flakey and will pass/fail for reasons unrelated to a specific change. TBD is fixing those flakey tests. For now just rerun the tests to see if they pass.

**Comment by catull** [comment]
How do I re-run the test ?

**Comment by krader1961** [comment]
> How do I re-run the test ?

On the systems you control just run `meson test`. On the Travis web UI there is a link to restart the build or job.

**Comment by krader1961** [comment]
Also, simply pushing an update, whether forced or not, to your fork will cause Travis to restart the tests.

**Comment by krader1961** [comment]
Also, at this time the Travis config does not include any BSD based systems such as macOS. So it is not unusual for a change to pass on Travis but for me to report a failure on my macOS and FreeBSD systems.

**Comment by catull** [comment]
I am afraid, I see no such option.
Perhaps only @siteshwar and yourself can restart Travis CI jobs.
Already knew how to re-run `meson test`.

**Comment by catull** [comment]
By the way, I only witness 3 cases of SIGSEVs, namely with:

`meson test -v types 'types(shcomp)' 'types(C.UTF-8)'`

That is in master, without any modification.

@krader1961 
Can you confirm this ?

I don't think the PR caused them.

**Comment by catull** [comment]
Went back in time so to speak, to a commit before I contributed.
That is easy, just a few days back.

Checking out at commit 3217a7085b862fb0a9705f925894dc2a849d816c, the logs state:
```
commit 3217a7085b862fb0a9705f925894dc2a849d816c.
Refs: [master]
Author:     Kurtis Rader <krader@skepticism.us>
AuthorDate: Mon Dec 18 21:47:09 2017 -0800
Commit:     Kurtis Rader <krader@skepticism.us>
CommitDate: Wed Dec 20 15:39:18 2017 -0800
```
This is how I reproduced the "SIGSEVs":
```shell
git reset --hard 3217a7085b862fb0a9705f925894dc2a849d816c
git clean -xfd
CC=gcc meson build   # have to specify CC=gcc, otherwise clang is taken directly or through alias
CC=gcc ninja -C build # ditto regarding CC
cd build
meson test -v types 'types(shcomp)' 'types(C.UTF-8)'
```
The output is:
```log
0   dump_backtrace + 69
1   handle_sigsegv + 25
2   _sigtramp + 26
3   3   ???                                 0x0000001600000000 0x0 + 94489280512
4   nv_putv + 562
5   put_chtype + 82
6   nv_putv + 520
7   nv_putval + 484
8   nv_open + 3936
9   sh_setlist + 7404
10  sh_exec + 4884
11  b_dot_cmd + 1721
12  sh_funct + 665
13  sh_fun_20120720 + 1077
14  type_init + 183
15  nv_settype + 1211
16  setall + 3755
17  b_typeset + 3659
18  sh_exec + 9057
19  exfile + 3343
20  sh_main + 4125
21  main + 38
22  start + 1
0   dump_backtrace + 69
1   handle_sigsegv + 25
2   _sigtramp + 26
3   3   ???                                 0x0000001400000000 0x0 + 85899345920
4   nv_putv + 562
5   put_chtype + 82
6   nv_putv + 520
7   nv_putval + 484
8   nv_open + 3936
9   sh_setlist + 7404
10  sh_exec + 4884
11  b_dot_cmd + 1721
12  sh_funct + 665
13  sh_fun_20120720 + 1077
14  type_init + 183
15  nv_settype + 1211
16  setall + 3755
17  b_typeset + 3659
18  sh_exec + 9057
19  exfile + 3343
20  sh_main + 4125
21  main + 38
22  start + 1
23  23  ???                                 0x0000000000000002 0x0 + 2
1/3 types                                   OK       0.14 s
2/3 types(C.UTF-8)                          OK       0.14 s
0   dump_backtrace + 69
1   handle_sigsegv + 25
2   _sigtramp + 26
3   3   ???                                 0x0000001400000000 0x0 + 85899345920
4   nv_putv + 562
5   put_chtype + 82
6   nv_putv + 520
7   nv_putval + 484
8   nv_open + 3936
9   sh_setlist + 7404
10  sh_exec + 4884
11  b_dot_cmd + 1721
12  sh_funct + 665
13  sh_fun_20120720 + 1077
14  type_init + 183
15  nv_settype + 1211
16  setall + 3755
17  b_typeset + 3659
18  sh_exec + 9057
19  exfile + 3343
20  sh_main + 4125
21  main + 38
22  start + 1
23  23  ???                                 0x0000000000000002 0x0 + 2
3/3 types(shcomp)                           OK       0.24 s

OK:         3
FAIL:       0
SKIP:       0
TIMEOUT:    0
```

**Comment by krader1961** [comment]
Merged. Thanks for all this work, @catull. Scut work like this isn't fun but reducing compiler (or lint tool) warnings is important as doing so makes it much easier to notice when a change introduces a potential problem.

**Comment by catull** [comment]
Not sure what that means, "scut work".

"[Scut](https://www.merriam-webster.com/dictionary/scut)" means "a short erect tail (as of a hare)"

Looked up [scut work](https://www.merriam-webster.com/dictionary/scut%20work) and noticed it makes a reference to "menial".
Another word not familiar to me; now that word means "servant" [1].

I can only assume you did not mean to define our relationship as "master and servant".

After more than 30 years of ob_serving_ the English language - as a classical humanist[2] - your language never stops to puzzle me, weekly.

[1] "menial" could be related to "mansio, -nis" (latin), meaning the house (of a noble man).  Modern English "Mansion" is what stems from it.

[2] I have studied and learned Latin, German, English, French and a little Russian.
My mother tongue is Italian.

**Pull request closed without merging**
