### PR TITLE
Remove 'lib' feature test from libast

### PR DESCRIPTION
**Pull request by siteshwar**

### CODE REVIEW

**Comment by krader1961** [comment]
There might be unusual platforms we want to support which this change might break building on (e.g., Haiku). But I'd rather remove all that code now and deal with making it build on those platforms in the future when someone asks that their favorite oddball platform be supported.

However, as usual macOS is slightly behind the times since it does not provide `pipe2()`. Also, there is no `sys/filio.h` header on Ubuntu 16.10 or OpenSUSE LEAP.

**Comment by siteshwar** [comment]
Clean build works fine for me on openSUSE.

**Comment by krader1961** [comment]
> Clean build works fine for me on openSUSE.

I have a script that I use to test these changes which forces a clean build. However, it does not directly modify the content of directories like the */features/* directories. I manually removed the *build* directory then did `meson; ninja` on OpenSUSE 42.3 and it still fails:

```
In file included from ../src/cmd/ksh93/include/edit.h:39:0,
                 from ../src/cmd/ksh93/sh/defs.c:27:
../src/cmd/ksh93/include/terminal.h:69:24: fatal error: sys/filio.h: No such file or directory
 # include <sys/filio.h>
                        ^
```

**Comment by siteshwar** [comment]
I have added a commit to fix compilation on macOS.

**Pull request merged**
